# All proposals must follow the template, so disallow creating blank issues.
blank_issues_enabled: false

contact_links:
  - name: Share and discuss ideas
    url: https://github.com/godotengine/godot-proposals/discussions
    about: Share ideas or start discussions about improvements for Godot.

  - name: Report a bug
    url: https://github.com/godotengine/godot
    about: Report bugs or problems on the main Godot repository.
